name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Node.js environment
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: '20'  # You can specify Node.js 20, or leave it to latest

    - name: Install dependencies
      run: npm install

    - name: Lint HTML files
      run: npx htmlhint 'src/html/**/*.html'

    - name: Lint CSS files
      run: npx stylelint 'src/css/**/*.css'

    - name: Lint JavaScript files
      run: npx eslint 'src/js/**/*.js'

    - name: Build project (if using a build tool like Webpack)
      run: npm run build

    - name: Run tests (optional)
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    # Deploy to GitHub Pages (or any other platform you use)
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Updated to v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src/html
